name: HorusLutar
main: me.king.lutar.Main
version: 1.0.0
description: Plugin de X1 Feito por SrPuti_;
author: [SrPuti_]
commands:
  x1:
    description: Comando para membros!
  x1admin:
    description: Comando para Administradores!
  mito:
    description: Comando para visualizar o mito do PVP